version: '3.8'

services:
    proxy:
        image: caddy:2
        restart: unless-stopped
        depends_on:
            - ui
            - api
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './Caddyfile:/etc/caddy/Caddyfile'
            - '/data'

    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: api
        container_name: api-preview
        restart: unless-stopped
        environment:
            - NODE_ENV=preview
            - PORT=3000
        expose:
            - '3000'

    ui:
        build:
            context: .
            dockerfile: Dockerfile
            target: ui
        container_name: ui-preview
        restart: unless-stopped
        depends_on:
            - api
        environment:
            - NODE_ENV=preview
        expose:
            - '8080'
