version: '3.9'

services:
    proxy:
        image: caddy:2
        restart: unless-stopped
        command: |
            caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
        depends_on:
            - ui
            - api
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/data'
            - './Caddyfile:/etc/caddy/Caddyfile:ro'

    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: api
        restart: unless-stopped
        container_name: api-preview
        environment:
            - NODE_ENV=preview
            - PORT=3000
        expose:
            - '3000'

    ui:
        build:
            context: .
            dockerfile: Dockerfile
            target: ui
        restart: unless-stopped
        container_name: ui-preview
        depends_on:
            - api
        environment:
            - NODE_ENV=preview
        expose:
            - '8080'

    workflows:
        build:
            context: .
            dockerfile: Dockerfile
            target: workflows
        restart: unless-stopped
        container_name: workflows-preview
        environment:
            - NODE_ENV=preview
