version: '3.9'

services:
    proxy:
        image: caddy:2
        restart: unless-stopped
        command: "caddy reverse-proxy --from '${PULLPREVIEW_PUBLIC_DNS}' --to ui:80"
        depends_on:
            - ui
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/data'
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: api
        restart: unless-stopped
        container_name: api-preview
        environment:
            - NODE_ENV=preview
            - PORT=3000
        expose:
            - '3000'

    ui:
        build:
            context: .
            dockerfile: Dockerfile
            target: ui
        restart: unless-stopped
        container_name: ui-preview
        depends_on:
            - api
        environment:
            - NODE_ENV=preview
        expose:
            - '8080'
