version: '3.9'

services:
    proxy:
        image: caddy:2
        restart: unless-stopped
        command: "caddy reverse-proxy --from '${PULLPREVIEW_PUBLIC_DNS}' --to ui:8080"
        depends_on:
            - ui
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/data'
        networks:
            - pullpreview-network

    ui:
        build:
            context: .
            dockerfile: Dockerfile
            target: ui
        restart: unless-stopped
        container_name: ui
        expose:
            - '8080'
        networks:
            - pullpreview-network

volumes:
    ui_caddy_data:

networks:
    pullpreview-network:
        external: true
