# .github/workflows/pullpreview.yml
name: PullPreview
on:
    push:
        branches: [main]
    pull_request:
        types: [labeled, unlabeled, synchronize, closed, reopened]

concurrency: ${{ github.ref }}

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read # to fetch code (actions/checkout)
            deployments: write # to delete deployments
            pull-requests: write # to remove labels
            statuses: write # to create commit status
        steps:
            - uses: actions/checkout@v2
            - uses: pullpreview/action@v5
              with:
                  # A staging environment will always exist for the master branch
                  always_on: main
                  # PullPreview will use those 2 files when running docker-compose up
                  compose_files: docker-compose.pullpreview.yml

              env:
                  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                  AWS_REGION: 'us-east-1'
